CREATE TABLE IF NOT EXISTS students(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
curp VARCHAR(18) NOT NULL UNIQUE,
account_number VARCHAR(10) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS courses(
	id INT NOt NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
price DECIMAL(14,2)
);
CREATE TABLE IF NOT EXISTS teachers(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
topic VARCHAR(30),
courses_id INT NOt NULL,
FOREIGN KEY (courses_id) REFERENCES courses(id)
);
CREATE TABLE IF NOT EXISTS students_courses(
	student_id VARCHAR(30) NOT NULL,
	course_id VARCHAR(30) NOT NULL,
datecourse DATE NOT NULL
FOREIGN KEY (students_id) REFERENCES students(id)
FOREIGN KEY (courses_id) REFERENCES courses(id)
);
